name: Update Google Scholar stats

on:
  schedule:
    - cron: "13 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Google Scholar profile
        run: |
          pip install scholarly matplotlib
          python <<'PY'
          from scholarly import scholarly
          import json, datetime, matplotlib.pyplot as plt

          USER_ID = "LJV0pHQAAAAJ"  # your scholar ID
          author = scholarly.search_author_id(USER_ID)
          data = {
              "name": author.name,
              "citations_all": author.citedby,
              "citations_5y": author.citedby5y,
              "h_index": author.hindex,
              "i10_index": author.i10index,
              "yearly_citations": author.cites_per_year,
              "updated": datetime.datetime.utcnow().isoformat() + "Z"
          }
          # Save JSON
          with open('gscholar.json', 'w') as f:
              json.dump(data, f, indent=2)

          # Save simple SVG chart
          years = sorted(data["yearly_citations"].keys())
          counts = [data["yearly_citations"][y] for y in years]
          plt.figure(figsize=(4,1.5))
          plt.bar(years, counts, color="#2E3D48")
          plt.xticks(years, rotation=45, fontsize=6)
          plt.yticks(fontsize=6)
          plt.tight_layout()
          plt.savefig("assets/gs_citations.svg", format="svg")
          PY

      - name: Commit updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Google Scholar stats"
          file_pattern: gscholar.json assets/gs_citations.svg
